# RocketMQ Broker 配置
brokerClusterName = DefaultCluster
brokerName = broker-auto
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 监听地址 (0.0.0.0 让容器外部可以访问)
brokerIP1 = 0.0.0.0
listenPort = 10911
# 开启 SQL 过滤
enablePropertyFilter = true
